### ISSUE TITLE
[wildfly+jdk8] failure because of vfs support

### ISSUE THREAD

**Issue by gdrouet** [rmuller/infomas-asl#29]
Hi,

I get an error when scanning classes inside WEB-INF/lib. It's easy to reproduce: just "mvn clean install" on [this project](https://github.com/wuic/wuic-samples/tree/wuic-0.5.x-snapshot/js-sprite-sample) and deploy the .war file in Wildfly.

Here's the stacktrace:
2014-11-19 14:12:20,756 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./wuic-sample-js-sprite: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./wuic-sample-js-sprite: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_11]
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: URI scheme is not "file"
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:219)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:87)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.start(UndertowDeploymentService.java:72)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
	... 3 more
Caused by: java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(File.java:421) [rt.jar:1.8.0_11]
	at eu.infomas.annotation.AnnotationDetector.toFile(AnnotationDetector.java:335)
	at eu.infomas.annotation.AnnotationDetector.detect(AnnotationDetector.java:276)
	at com.github.wuic.util.AnnotationDetectorScanner.scan(AnnotationDetectorScanner.java:75)
	at com.github.wuic.config.ObjectBuilderFactory.<init>(ObjectBuilderFactory.java:163)
	at com.github.wuic.ContextBuilder.<init>(ContextBuilder.java:190)
	at com.github.wuic.ContextBuilder.<init>(ContextBuilder.java:215)
	at com.github.wuic.WuicFacade.<init>(WuicFacade.java:178)
	at com.github.wuic.WuicFacadeBuilder.build(WuicFacadeBuilder.java:283)
	at com.github.wuic.jee.WuicServletContextListener.contextInitialized(WuicServletContextListener.java:94)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:173)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:190)
	... 7 more

**Comment by gdrouet** [comment]
Just for your information, there is an interesting PR for jersey: https://github.com/jersey/jersey/pull/100

**Comment by rmuller** [comment]
This is indeed VERY interesting. Thanks! Currently I have no time, but soon this issue will be closed :)

**Comment by rmuller** [comment]
Finally implemented a fix for this issue. Tested with WildFly 8.2.0, 9.0.1.

https://github.com/rmuller/infomas-asl/blob/master/annotation-detector/README.md
