### ISSUE TITLE
ClassCastException ZipURLConnection cannot JarURLConnection

### ISSUE THREAD

**Issue by culmat** [rmuller/infomas-asl#30]
When running in Weblogic I get the following:
```
weblogic.application.ModuleException: [HTTP:101216]Servlet: "com.baloise.rest.Application" failed to preload on startup in Web application: "
java.lang.ClassCastException: weblogic.utils.zip.ZipURLConnection cannot be cast to java.net.JarURLConnection
        at eu.infomas.annotation.AnnotationDetector.detect(AnnotationDetector.java:295)
        at com.baloise.rest.Application.addFromClassPath(Application.java:59)
        at com.baloise.rest.Application.getClasses(Application.java:26)
```

**Comment by rmuller** [comment]
I was able to reproduce this issue. It is fixed in the master branch (version 3.0.x).

Please confirm if everything now works as expected.
