### ISSUE TITLE
When I run it in android, it throw exception when AnnotationDetector.detect()?

### ISSUE THREAD

**Issue by whoooami** [rmuller/infomas-asl#38]
java.lang.NullPointerException: Attempt to get length of null array
                                                              at eu.infomas.annotation.FileIterator.addReverse(FileIterator.java:117)
                                                              at eu.infomas.annotation.FileIterator.next(FileIterator.java:105)
                                                              at eu.infomas.annotation.FileIterator.next(FileIterator.java:106)
                                                              at eu.infomas.annotation.ClassFileIterator.next(ClassFileIterator.java:84)
                                                              at eu.infomas.annotation.AnnotationDetector.detect(AnnotationDetector.java:344)
                                                              at eu.infomas.annotation.AnnotationDetector.detect(AnnotationDetector.java:248)

**Comment by rmuller** [comment]
AFAIK android does not use jar-files (no JVM but Android Runtime, ART), so it is expected that it does not work on Android.

**Comment by whoooami** [comment]
Thank you!
